version: "2"

networks:
   fabric:

services:
   rca-org0:
      container_name: rca-org0
      image: hyperledger/fabric-ca:${DOCKER_FABRIC_CA_VERSION}
      command: /bin/bash -c 'fabric-ca-server start -d -b rca-org0-admin:rca-org0-adminpw --port 7053'
      environment:
         - FABRIC_CA_SERVER_HOME=/tmp/hyperledger/fabric-ca/crypto
         - FABRIC_CA_SERVER_TLS_ENABLED=true
         - FABRIC_CA_SERVER_CSR_CN=rca-org0
         - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
         - FABRIC_CA_SERVER_DEBUG=true
      volumes:
         - ./crypto/org0/ca:/tmp/hyperledger/fabric-ca
      ports:
         - 7053:7053
      networks:
         - fabric

   rca-org1:
      container_name: rca-org1
      image: hyperledger/fabric-ca:${DOCKER_FABRIC_CA_VERSION}
      command: /bin/bash -c 'fabric-ca-server start -d -b rca-org1-admin:rca-org1-adminpw'
      environment:
         - FABRIC_CA_SERVER_HOME=/tmp/hyperledger/fabric-ca/crypto
         - FABRIC_CA_SERVER_TLS_ENABLED=true
         - FABRIC_CA_SERVER_CSR_CN=rca-org1
         - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
         - FABRIC_CA_SERVER_DEBUG=true
      volumes:
         - ./crypto/org1/ca:/tmp/hyperledger/fabric-ca
      ports:
         - 7054:7054
      networks:
         - fabric

   rca-org2:
      container_name: rca-org2
      image: hyperledger/fabric-ca:${DOCKER_FABRIC_CA_VERSION}
      command: /bin/bash -c 'fabric-ca-server start -d -b rca-org2-admin:rca-org2-adminpw --port 7055'
      environment:
         - FABRIC_CA_SERVER_HOME=/tmp/hyperledger/fabric-ca/crypto
         - FABRIC_CA_SERVER_TLS_ENABLED=true
         - FABRIC_CA_SERVER_CSR_CN=rca-org2
         - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
         - FABRIC_CA_SERVER_DEBUG=true
      volumes:
         - ./crypto/org2/ca:/tmp/hyperledger/fabric-ca
      ports:
         - 7055:7055
      networks:
         - fabric
