version: '2'

networks:
  fabric:

services:
  web-server:
    container_name: web-server
    image: node:10
    tty: true
    stdin_open: true
    working_dir: /usr/src/app
    command: "sh -c 'rm -rf  wallet/admin && sh ./updateKeystore.sh && node enrollAdmin.js && npm install && npm start'"
    volumes:
      - ./web-app/server:/usr/src/app
      - ./crypto:/usr/src/crypto
    environment:
      - PORT=4000
    ports:
      - 4000:4000
    networks:
      - fabric
#  web-client:
#    container_name: web-client
#    build:
#      context: ./web-app/client
#      dockerfile: Dockerfile
#    volumes:
#      - '.:/app'
#      - '/app/node_modules'
#    ports:
#s     - 3001:3000
#    environment:
#      - CHOKIDAR_USEPOLLING=true
