version: "2"

networks:
  fabric:

services:
  peer1-org1:
    container_name: peer1.org1
    image: hyperledger/fabric-peer:${DOCKER_FABRIC_PEER_VERSION}
    environment:
      - CORE_PEER_ID=peer1.org1
      - CORE_PEER_ADDRESS=peer1.org1:7051
      - CORE_PEER_LOCALMSPID=org1MSP
      - CORE_PEER_MSPCONFIGPATH=/org1/peer1/msp
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_fabric
      - FABRIC_LOGGING_SPEC=debug
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couch.peer1.org1:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=${COUCHDB_USER_P1O1}
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=${COUCHDB_PW_P1O1}
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/org1/peer1/tls-msp/signcerts/cert.pem
      - CORE_PEER_TLS_KEY_FILE=/org1/peer1/tls-msp/keystore/key.pem
      - CORE_PEER_TLS_ROOTCERT_FILE=/org1/peer1/tls-msp/tlscacerts/tls-0-0-0-0-7052.pem
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1:7051
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/org1/peer1
    volumes:
      - /var/run:/host/var/run
      - ./crypto/org1/peer1:/org1/peer1
    depends_on:
      # orderer.org0
      - couch.peer1.org1
    networks:
      - fabric

  couch.peer1.org1:
    container_name: couch.peer1.org1
    image: hyperledger/fabric-couchdb:${DOCKER_FABRIC_COUCHDB_VERSION}
    environment:
      - COUCHDB_USER=${COUCHDB_USER_P1O1}
      - COUCHDB_PASSWORD=${COUCHDB_PW_P1O1}
    networks:
      - fabric

  peer2-org1:
    container_name: peer2.org1
    image: hyperledger/fabric-peer:${DOCKER_FABRIC_PEER_VERSION}
    environment:
      - CORE_PEER_ID=peer2.org1
      - CORE_PEER_ADDRESS=peer2.org1:7051
      - CORE_PEER_LOCALMSPID=org1MSP
      - CORE_PEER_MSPCONFIGPATH=/org1/peer2/msp
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_fabric
      - FABRIC_LOGGING_SPEC=debug
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couch.peer2.org1:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=${COUCHDB_USER_P2O1}
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=${COUCHDB_PW_P2O1}
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/org1/peer2/tls-msp/signcerts/cert.pem
      - CORE_PEER_TLS_KEY_FILE=/org1/peer2/tls-msp/keystore/key.pem
      - CORE_PEER_TLS_ROOTCERT_FILE=/org1/peer2/tls-msp/tlscacerts/tls-0-0-0-0-7052.pem
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.org1:7051
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/org1/peer2
    volumes:
      - /var/run:/host/var/run
      - ./crypto/org1/peer2:/org1/peer2
    depends_on:
      #- orderer.org0
      - couch.peer2.org1
    networks:
      - fabric

  couch.peer2.org1:
    container_name: couch.peer2.org1
    image: hyperledger/fabric-couchdb:${DOCKER_FABRIC_COUCHDB_VERSION}
    environment:
      - COUCHDB_USER=${COUCHDB_USER_P2O1}
      - COUCHDB_PASSWORD=${COUCHDB_PW_P2O1}
    networks:
      - fabric

  peer1-org2:
    container_name: peer1.org2
    image: hyperledger/fabric-peer:${DOCKER_FABRIC_PEER_VERSION}
    environment:
      - CORE_PEER_ID=peer1.org2
      - CORE_PEER_ADDRESS=peer1.org2:7051
      - CORE_PEER_LOCALMSPID=org2MSP
      - CORE_PEER_MSPCONFIGPATH=/org2/peer1/msp
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_fabric
      - FABRIC_LOGGING_SPEC=debug
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couch.peer1.org2:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=${COUCHDB_USER_P1O2}
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=${COUCHDB_PW_P1O2}
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/org2/peer1/tls-msp/signcerts/cert.pem
      - CORE_PEER_TLS_KEY_FILE=/org2/peer1/tls-msp/keystore/key.pem
      - CORE_PEER_TLS_ROOTCERT_FILE=/org2/peer1/tls-msp/tlscacerts/tls-0-0-0-0-7052.pem
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2:7051
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/org2/peer1
    volumes:
      - /var/run:/host/var/run
      - ./crypto/org2/peer1:/org2/peer1
    depends_on:
      #- orderer.org0
      - couch.peer1.org2
    networks:
      - fabric

  couch.peer1.org2:
    container_name: couch.peer1.org2
    image: hyperledger/fabric-couchdb:${DOCKER_FABRIC_COUCHDB_VERSION}
    environment:
      - COUCHDB_USER=${COUCHDB_USER_P1O2}
      - COUCHDB_PASSWORD=${COUCHDB_PW_P1O2}
    networks:
      - fabric

  peer2-org2:
    container_name: peer2.org2
    image: hyperledger/fabric-peer:${DOCKER_FABRIC_PEER_VERSION}
    environment:
      - CORE_PEER_ID=peer2-org2
      - CORE_PEER_ADDRESS=peer2.org2:7051
      - CORE_PEER_LOCALMSPID=org2MSP
      - CORE_PEER_MSPCONFIGPATH=/org2/peer2/msp
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_fabric
      - FABRIC_LOGGING_SPEC=debug
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couch.peer2.org2:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=${COUCHDB_USER_P2O2}
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=${COUCHDB_PW_P2O2}
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/org2/peer2/tls-msp/signcerts/cert.pem
      - CORE_PEER_TLS_KEY_FILE=/org2/peer2/tls-msp/keystore/key.pem
      - CORE_PEER_TLS_ROOTCERT_FILE=/org2/peer2/tls-msp/tlscacerts/tls-0-0-0-0-7052.pem
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.org2:7051
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/org2/peer2
    volumes:
      - /var/run:/host/var/run
      - ./crypto/org2/peer2:/org2/peer2
    depends_on:
      #- orderer.org0
      - couch.peer2.org2
    networks:
      - fabric

  couch.peer2.org2:
    container_name: couch.peer2.org2
    image: hyperledger/fabric-couchdb:${DOCKER_FABRIC_COUCHDB_VERSION}
    environment:
      - COUCHDB_USER=${COUCHDB_USER_P2O2}
      - COUCHDB_PASSWORD=${COUCHDB_PW_P2O2}
    networks:
      - fabric
