version: "2"

networks:
  fabric:

services:
  cli:
    container_name: cli
    image: hyperledger/fabric-tools:${DOCKER_FABRIC_TOOLS_VERSION}
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_ID=cli.org1
      - CORE_PEER_ADDRESS=peer1.org1:7051
      - CORE_PEER_LOCALMSPID=org1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_ROOTCERT_FILE=/tmp/hyperledger/crypto/org1/peer1/tls-msp/tlscacerts/tls-0-0-0-0-7052.pem
      - CORE_PEER_MSPCONFIGPATH=/tmp/hyperledger/crypto/org1/admin/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/org1
    command: sh
    volumes:
      #- ./crypto/org1/peer1:/tmp/hyperledger/org1/peer1
      - ./chaincodes:/opt/gopath/src/github.com/hyperledger/fabric-samples/chaincode
      #- ./crypto/org1/admin:/tmp/hyperledger/org1/admin
      - ./crypto:/tmp/hyperledger/crypto
      - ./setup/02-chaincode:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    networks:
      - fabric
